/**
 * Runtime regeneration of the Cursor / Copilot CLI rules-file content.
 *
 * The Cursor adapter and Copilot adapter both treat the rules file as the
 * dependable model-context-injection path (Cursor postToolUse `additional_context`
 * is unreliable per Cursor staff feedback; Copilot CLI hooks have no documented
 * `additionalContext` field). The hook binary calls these helpers on the
 * appropriate lifecycle events so the file is always up to date.
 *
 * Both writers are best-effort. Failures are logged via the caller; the hook
 * never fails the assistant session because of a rules-file write error.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { randomBytes } from 'node:crypto';

const CURSOR_RULES_REL = path.join('.cursor', 'rules', 'second-brain-context.mdc');
const COPILOT_INSTRUCTIONS_REL = path.join('.github', 'copilot-instructions.md');

/**
 * Atomic write — writes to a sibling tmp file and rename()s into place.
 * `rename` is atomic on POSIX, so a concurrent reader sees either the old
 * content or the new content, never a partial write. Falls back to a direct
 * write if `rename` fails (e.g. cross-device on a tmpfs override).
 */
function writeFileAtomic(target: string, content: string): void {
  const dir = path.dirname(target);
  fs.mkdirSync(dir, { recursive: true });
  const tmp = path.join(dir, `.${path.basename(target)}.${randomBytes(4).toString('hex')}.tmp`);
  fs.writeFileSync(tmp, content, 'utf8');
  try {
    fs.renameSync(tmp, target);
  } catch {
    fs.writeFileSync(target, content, 'utf8');
    try {
      fs.unlinkSync(tmp);
    } catch {
      /* ignore */
    }
  }
}

const COPILOT_SENTINEL_BEGIN = '<!-- begin:second-brain -->';
const COPILOT_SENTINEL_END = '<!-- end:second-brain -->';

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/** Cursor `.mdc` file with a fixed frontmatter block. Body is the live context. */
function buildCursorRulesFile(contextBlock: string): string {
  const trimmed = contextBlock.trim();
  return [
    '---',
    'description: Second Brain context (auto-generated)',
    'globs:',
    'alwaysApply: true',
    '---',
    '',
    '<!-- This file is regenerated by brain-hook on every Cursor sessionStart/stop. -->',
    '<!-- Do not edit manually; edits will be overwritten. -->',
    '',
    trimmed.length > 0 ? trimmed : '_(no context yet — start a Cursor session in this repo to populate this file.)_',
    '',
  ].join('\n');
}

/** Replace (or insert) the sentinel-delimited block in `existing`. */
export function upsertSentinelBlock(existing: string, blockBody: string): string {
  const begin = COPILOT_SENTINEL_BEGIN;
  const end = COPILOT_SENTINEL_END;
  const re = new RegExp(`${escapeRegExp(begin)}[\\s\\S]*?${escapeRegExp(end)}`, 'm');
  const replacement = `${begin}\n${blockBody.trim()}\n${end}`;
  if (re.test(existing)) return existing.replace(re, replacement);
  if (existing.length === 0) return `${replacement}\n`;
  return `${existing.replace(/\s+$/, '')}\n\n${replacement}\n`;
}

export interface RefreshResult {
  ok: boolean;
  path: string;
  reason?: string;
}

/** Regenerate Cursor's `.cursor/rules/second-brain-context.mdc`. */
export function refreshCursorRules(cwd: string, contextBlock: string): RefreshResult {
  const target = path.join(cwd, CURSOR_RULES_REL);
  try {
    writeFileAtomic(target, buildCursorRulesFile(contextBlock));
    return { ok: true, path: target };
  } catch (e) {
    return { ok: false, path: target, reason: e instanceof Error ? e.message : String(e) };
  }
}

/** Upsert the sentinel block inside `.github/copilot-instructions.md`. */
export function refreshCopilotInstructions(cwd: string, contextBlock: string): RefreshResult {
  const target = path.join(cwd, COPILOT_INSTRUCTIONS_REL);
  try {
    let existing = '';
    if (fs.existsSync(target)) {
      try {
        existing = fs.readFileSync(target, 'utf8');
      } catch {
        existing = '';
      }
    }
    const next = upsertSentinelBlock(existing, contextBlock);
    if (next !== existing) {
      writeFileAtomic(target, next);
    }
    return { ok: true, path: target };
  } catch (e) {
    return { ok: false, path: target, reason: e instanceof Error ? e.message : String(e) };
  }
}
