/**
 * GitHub Copilot CLI adapter — project-scope hooks + MCP + rules-file.
 *
 * Per plan §C and verified against docs.github.com:
 *   - Project scope hooks live at `<repo>/.github/hooks/second-brain.json`
 *     (documented). User-scope hook config is undocumented; we skip it
 *     with a warning.
 *   - MCP entry merges into `~/.copilot/mcp-config.json`.
 *   - Rules file `<repo>/.github/copilot-instructions.md` carries a
 *     sentinel-delimited block: `<!-- begin:second-brain --> ... <!-- end:second-brain -->`.
 *     We never overwrite content outside the sentinels.
 *   - `<repo>/AGENTS.md` is created only when missing (Copilot also reads it).
 *
 * Hooks are observe/policy only — there is no documented `additionalContext`
 * pre-tool injection field for Copilot CLI. The dependable injection path
 * is the rules file.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import type {
  Adapter,
  AdapterInstallOptions,
  AdapterInstallResult,
  AdapterUninstallOptions,
  AdapterUninstallResult,
  AdapterDetectResult,
} from './types.js';
import { resolveBrainMcpInvocation } from './mcp-resolve.js';
import { isRecord, writeJson, escapeRegExp } from './shared/json-file.js';
import { brainHookCommand as renderHookCommand, type HookVerb, type Phase } from './shared/hook-events.js';
import { upsertSentinelDedup, removeSentinelEntries, upsertSentinelBlock as renderSentinelBlock } from './shared/sentinel.js';
import { upsertMcpServersJson } from './shared/mcp-merge.js';

const COPILOT_EVENTS = [
  'sessionStart',
  'sessionEnd',
  'userPromptSubmitted',
  'preToolUse',
  'postToolUse',
  'errorOccurred',
] as const;
type CopilotEvent = (typeof COPILOT_EVENTS)[number];

/** Host event → brain verb+phase mapping for GitHub Copilot CLI. */
const COPILOT_EVENT_MAP: Record<CopilotEvent, { verb: HookVerb; phase?: Phase }> = {
  sessionStart: { verb: 'session-start' },
  sessionEnd: { verb: 'session-end' },
  userPromptSubmitted: { verb: 'prompt-submit' },
  preToolUse: { verb: 'tool-use', phase: 'pre' },
  postToolUse: { verb: 'tool-use', phase: 'post' },
  errorOccurred: { verb: 'stop' },
};

interface CopilotHookCommand {
  command: string;
}

interface CopilotHooksFile {
  version: 1;
  hooks: Record<string, CopilotHookCommand[]>;
}

const SENTINEL_BEGIN = '<!-- begin:second-brain -->';
const SENTINEL_END = '<!-- end:second-brain -->';

function brainHookCommand(event: CopilotEvent, override?: string): string {
  const { verb, phase } = COPILOT_EVENT_MAP[event];
  return renderHookCommand({ verb, phase, adapter: 'copilot', bin: override });
}

function resolveProjectHooksPath(cwd: string): string {
  return path.join(cwd, '.github', 'hooks', 'second-brain.json');
}

function resolveMcpPath(home: string): string {
  return path.join(home, '.copilot', 'mcp-config.json');
}

function resolveInstructionsPath(cwd: string): string {
  return path.join(cwd, '.github', 'copilot-instructions.md');
}

function resolveAgentsMdPath(cwd: string): string {
  return path.join(cwd, 'AGENTS.md');
}

function loadHooksFile(p: string): CopilotHooksFile {
  const fallback: CopilotHooksFile = { version: 1, hooks: {} };
  try {
    const raw = fs.readFileSync(p, 'utf8');
    if (!raw.trim()) return fallback;
    const parsed: unknown = JSON.parse(raw);
    if (!isRecord(parsed)) return fallback;
    const hooks: Record<string, CopilotHookCommand[]> = {};
    if (isRecord(parsed.hooks)) {
      for (const [k, v] of Object.entries(parsed.hooks)) {
        if (!Array.isArray(v)) continue;
        const cmds: CopilotHookCommand[] = [];
        for (const c of v) {
          if (isRecord(c) && typeof c.command === 'string') {
            cmds.push({ command: c.command });
          }
        }
        hooks[k] = cmds;
      }
    }
    return { version: 1, hooks };
  } catch {
    return fallback;
  }
}

/**
 * Replace (or insert) the second-brain sentinel block inside `existing`.
 * Re-exported from the shared toolkit so callers of `../copilot.js` keep the
 * same import path; the default markers match this adapter's sentinels.
 */
export function upsertSentinelBlock(existing: string, blockBody: string): string {
  return renderSentinelBlock(existing, blockBody, { begin: SENTINEL_BEGIN, end: SENTINEL_END });
}

function defaultInstructionsBlock(): string {
  return [
    '## Second Brain — repository context (auto-managed)',
    '',
    'This block is regenerated by `brain-hook` on every session.',
    'Do not edit manually; edits will be overwritten.',
    '',
    'Recent decisions, WIP and patterns will appear here once a Copilot CLI session populates them.',
  ].join('\n');
}

function installImpl(opts: AdapterInstallOptions): AdapterInstallResult {
  const warnings: string[] = [];
  const auxFiles: string[] = [];
  const added: string[] = [];

  if (opts.scope === 'user') {
    // We still wire MCP for user scope but never write to undocumented hook paths.
    warnings.push('user-scope Copilot CLI hooks are undocumented — installing MCP only');
    const mcpPath = resolveMcpPath(opts.home);
    upsertMcp(mcpPath, auxFiles, warnings);
    return {
      configPath: mcpPath,
      addedEvents: added,
      auxFiles,
      warnings,
      skipped: 'hooks skipped (user scope undocumented); MCP installed',
    };
  }

  // Project scope — full install.
  const hooksPath = resolveProjectHooksPath(opts.cwd);
  const file = loadHooksFile(hooksPath);
  for (const event of COPILOT_EVENTS) {
    const cmd = brainHookCommand(event, opts.hookCommand);
    const list = file.hooks[event] ?? [];
    const { changed } = upsertSentinelDedup(list, cmd, (command) => ({ command }));
    if (changed) added.push(event);
    file.hooks[event] = list;
  }
  writeJson(hooksPath, file);

  // MCP — user-scope only.
  const mcpPath = resolveMcpPath(opts.home);
  upsertMcp(mcpPath, auxFiles, warnings);

  // Rules file: copilot-instructions.md.
  const instructionsPath = resolveInstructionsPath(opts.cwd);
  let existing = '';
  if (fs.existsSync(instructionsPath)) {
    try {
      existing = fs.readFileSync(instructionsPath, 'utf8');
    } catch {
      existing = '';
    }
  }
  const next = upsertSentinelBlock(existing, defaultInstructionsBlock());
  if (next !== existing) {
    fs.mkdirSync(path.dirname(instructionsPath), { recursive: true });
    fs.writeFileSync(instructionsPath, next, 'utf8');
    auxFiles.push(instructionsPath);
  }

  // AGENTS.md — only if missing, never overwrite.
  const agentsPath = resolveAgentsMdPath(opts.cwd);
  if (!fs.existsSync(agentsPath)) {
    fs.writeFileSync(
      agentsPath,
      [
        '# Repo agents context',
        '',
        'This file is read by GitHub Copilot CLI alongside `.github/copilot-instructions.md`.',
        '',
        '<!-- See .github/copilot-instructions.md for the auto-managed Second Brain block. -->',
        '',
      ].join('\n'),
      'utf8',
    );
    auxFiles.push(agentsPath);
  }

  return {
    configPath: hooksPath,
    addedEvents: added,
    auxFiles,
    warnings,
  };
}

function upsertMcp(mcpPath: string, auxFiles: string[], warnings: string[]): void {
  const resolved = resolveBrainMcpInvocation();
  if (resolved.warning) warnings.push(resolved.warning);
  if (!resolved.invocation) return;
  const { written } = upsertMcpServersJson(mcpPath, resolved.invocation);
  if (written) auxFiles.push(mcpPath);
}

function uninstallImpl(opts: AdapterUninstallOptions): AdapterUninstallResult {
  const removed: string[] = [];
  const warnings: string[] = [];
  const hooksPath = resolveProjectHooksPath(opts.cwd);
  if (fs.existsSync(hooksPath)) {
    const file = loadHooksFile(hooksPath);
    for (const event of Object.keys(file.hooks)) {
      const cmds = file.hooks[event];
      const { list: filtered, removed: didRemove } = removeSentinelEntries(cmds);
      if (didRemove) removed.push(event);
      if (filtered.length > 0) file.hooks[event] = filtered;
      else delete file.hooks[event];
    }
    writeJson(hooksPath, file);
  }
  // Remove sentinel block from instructions file (preserve other content).
  const instructionsPath = resolveInstructionsPath(opts.cwd);
  if (fs.existsSync(instructionsPath)) {
    try {
      const raw = fs.readFileSync(instructionsPath, 'utf8');
      const re = new RegExp(`${escapeRegExp(SENTINEL_BEGIN)}[\\s\\S]*?${escapeRegExp(SENTINEL_END)}\\n*`, 'm');
      const next = raw.replace(re, '');
      if (next !== raw) {
        fs.writeFileSync(instructionsPath, next, 'utf8');
      }
    } catch {
      // ignore
    }
  }
  return { configPath: hooksPath, removed, warnings };
}

function detectImpl(home: string, _cwd: string): AdapterDetectResult {
  const installed = fs.existsSync(path.join(home, '.copilot'));
  return { installed, warnings: [] };
}

export const copilotAdapter: Adapter = {
  name: 'copilot',
  // Hooks are observe/policy only; rules file is the dependable injection path
  // and the rules file is regenerated by brain-hook on each sessionStart.
  supportsPreContextInjection: false,
  supportsPromptSubmitInjection: false,
  supportsSessionStartInjection: true,
  install: installImpl,
  uninstall: uninstallImpl,
  detect: detectImpl,
};
