/**
 * GitHub Copilot CLI adapter — project-scope hooks + MCP + rules-file.
 *
 * Per plan §C and verified against docs.github.com:
 *   - Project scope hooks live at `<repo>/.github/hooks/second-brain.json`
 *     (documented). User-scope hook config is undocumented; we skip it
 *     with a warning.
 *   - MCP entry merges into `~/.copilot/mcp-config.json`.
 *   - Rules file `<repo>/.github/copilot-instructions.md` carries a
 *     sentinel-delimited block: `<!-- begin:second-brain --> ... <!-- end:second-brain -->`.
 *     We never overwrite content outside the sentinels.
 *   - `<repo>/AGENTS.md` is created only when missing (Copilot also reads it).
 *
 * Hooks are observe/policy only — there is no documented `additionalContext`
 * pre-tool injection field for Copilot CLI. The dependable injection path
 * is the rules file.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import type {
  Adapter,
  AdapterInstallOptions,
  AdapterInstallResult,
  AdapterUninstallOptions,
  AdapterUninstallResult,
  AdapterDetectResult,
} from './types.js';
import { HOOK_SENTINEL } from './types.js';

const COPILOT_EVENTS = [
  'sessionStart',
  'sessionEnd',
  'userPromptSubmitted',
  'preToolUse',
  'postToolUse',
  'errorOccurred',
] as const;
type CopilotEvent = (typeof COPILOT_EVENTS)[number];

interface CopilotHookCommand {
  command: string;
}

interface CopilotHooksFile {
  version: 1;
  hooks: Record<string, CopilotHookCommand[]>;
}

const SENTINEL_BEGIN = '<!-- begin:second-brain -->';
const SENTINEL_END = '<!-- end:second-brain -->';

function brainHookCommand(event: CopilotEvent, override?: string): string {
  const bin = override ?? 'brain-hook';
  const flag = '--adapter copilot';
  switch (event) {
    case 'sessionStart':
      return `${bin} session-start ${flag} ${HOOK_SENTINEL}`;
    case 'sessionEnd':
      return `${bin} session-end ${flag} ${HOOK_SENTINEL}`;
    case 'userPromptSubmitted':
      return `${bin} prompt-submit ${flag} ${HOOK_SENTINEL}`;
    case 'preToolUse':
      return `${bin} tool-use --phase pre ${flag} ${HOOK_SENTINEL}`;
    case 'postToolUse':
      return `${bin} tool-use --phase post ${flag} ${HOOK_SENTINEL}`;
    case 'errorOccurred':
      return `${bin} stop ${flag} ${HOOK_SENTINEL}`;
  }
}

function resolveProjectHooksPath(cwd: string): string {
  return path.join(cwd, '.github', 'hooks', 'second-brain.json');
}

function resolveMcpPath(home: string): string {
  return path.join(home, '.copilot', 'mcp-config.json');
}

function resolveInstructionsPath(cwd: string): string {
  return path.join(cwd, '.github', 'copilot-instructions.md');
}

function resolveAgentsMdPath(cwd: string): string {
  return path.join(cwd, 'AGENTS.md');
}

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}

function loadHooksFile(p: string): CopilotHooksFile {
  const fallback: CopilotHooksFile = { version: 1, hooks: {} };
  try {
    const raw = fs.readFileSync(p, 'utf8');
    if (!raw.trim()) return fallback;
    const parsed: unknown = JSON.parse(raw);
    if (!isRecord(parsed)) return fallback;
    const hooks: Record<string, CopilotHookCommand[]> = {};
    if (isRecord(parsed.hooks)) {
      for (const [k, v] of Object.entries(parsed.hooks)) {
        if (!Array.isArray(v)) continue;
        const cmds: CopilotHookCommand[] = [];
        for (const c of v) {
          if (isRecord(c) && typeof c.command === 'string') {
            cmds.push({ command: c.command });
          }
        }
        hooks[k] = cmds;
      }
    }
    return { version: 1, hooks };
  } catch {
    return fallback;
  }
}

function writeJson(p: string, value: unknown): void {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, JSON.stringify(value, null, 2) + '\n', 'utf8');
}

/**
 * Replace (or insert) a sentinel-delimited block inside `existing`. Content
 * outside the sentinels is preserved verbatim.
 */
export function upsertSentinelBlock(existing: string, blockBody: string): string {
  const begin = SENTINEL_BEGIN;
  const end = SENTINEL_END;
  const re = new RegExp(`${escapeRegExp(begin)}[\\s\\S]*?${escapeRegExp(end)}`, 'm');
  const replacement = `${begin}\n${blockBody.trim()}\n${end}`;
  if (re.test(existing)) return existing.replace(re, replacement);
  if (existing.length === 0) return `${replacement}\n`;
  return `${existing.replace(/\s+$/, '')}\n\n${replacement}\n`;
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function defaultInstructionsBlock(): string {
  return [
    '## Second Brain — repository context (auto-managed)',
    '',
    'This block is regenerated by `brain-hook` on every session.',
    'Do not edit manually; edits will be overwritten.',
    '',
    'Recent decisions, WIP and patterns will appear here once a Copilot CLI session populates them.',
  ].join('\n');
}

function installImpl(opts: AdapterInstallOptions): AdapterInstallResult {
  const warnings: string[] = [];
  const auxFiles: string[] = [];
  const added: string[] = [];

  if (opts.scope === 'user') {
    // We still wire MCP for user scope but never write to undocumented hook paths.
    warnings.push('user-scope Copilot CLI hooks are undocumented — installing MCP only');
    const mcpPath = resolveMcpPath(opts.home);
    upsertMcp(mcpPath, auxFiles);
    return {
      configPath: mcpPath,
      addedEvents: added,
      auxFiles,
      warnings,
      skipped: 'hooks skipped (user scope undocumented); MCP installed',
    };
  }

  // Project scope — full install.
  const hooksPath = resolveProjectHooksPath(opts.cwd);
  const file = loadHooksFile(hooksPath);
  for (const event of COPILOT_EVENTS) {
    const cmd = brainHookCommand(event, opts.hookCommand);
    const list = file.hooks[event] ?? [];
    let matched = false;
    let updated = false;
    for (const item of list) {
      if (item.command === cmd) {
        matched = true;
      } else if (item.command.includes(HOOK_SENTINEL)) {
        item.command = cmd;
        matched = true;
        updated = true;
      }
    }
    if (!matched) {
      list.push({ command: cmd });
      added.push(event);
    } else if (updated) {
      added.push(event);
    }
    file.hooks[event] = list;
  }
  writeJson(hooksPath, file);

  // MCP — user-scope only.
  const mcpPath = resolveMcpPath(opts.home);
  upsertMcp(mcpPath, auxFiles);

  // Rules file: copilot-instructions.md.
  const instructionsPath = resolveInstructionsPath(opts.cwd);
  let existing = '';
  if (fs.existsSync(instructionsPath)) {
    try {
      existing = fs.readFileSync(instructionsPath, 'utf8');
    } catch {
      existing = '';
    }
  }
  const next = upsertSentinelBlock(existing, defaultInstructionsBlock());
  if (next !== existing) {
    fs.mkdirSync(path.dirname(instructionsPath), { recursive: true });
    fs.writeFileSync(instructionsPath, next, 'utf8');
    auxFiles.push(instructionsPath);
  }

  // AGENTS.md — only if missing, never overwrite.
  const agentsPath = resolveAgentsMdPath(opts.cwd);
  if (!fs.existsSync(agentsPath)) {
    fs.writeFileSync(
      agentsPath,
      [
        '# Repo agents context',
        '',
        'This file is read by GitHub Copilot CLI alongside `.github/copilot-instructions.md`.',
        '',
        '<!-- See .github/copilot-instructions.md for the auto-managed Second Brain block. -->',
        '',
      ].join('\n'),
      'utf8',
    );
    auxFiles.push(agentsPath);
  }

  return {
    configPath: hooksPath,
    addedEvents: added,
    auxFiles,
    warnings,
  };
}

function upsertMcp(mcpPath: string, auxFiles: string[]): void {
  let mcp: { mcpServers: Record<string, unknown> } = { mcpServers: {} };
  if (fs.existsSync(mcpPath)) {
    try {
      const raw = fs.readFileSync(mcpPath, 'utf8');
      if (raw.trim()) {
        const parsed: unknown = JSON.parse(raw);
        if (isRecord(parsed)) {
          const servers = parsed.mcpServers;
          mcp = { mcpServers: isRecord(servers) ? { ...servers } : {} };
          for (const [k, v] of Object.entries(parsed)) {
            if (k !== 'mcpServers') {
              const obj: Record<string, unknown> = mcp;
              obj[k] = v;
            }
          }
        }
      }
    } catch {
      // fall through to defaults
    }
  }
  if (!mcp.mcpServers['second-brain']) {
    mcp.mcpServers['second-brain'] = {
      command: 'brain',
      args: ['mcp'],
    };
    writeJson(mcpPath, mcp);
    auxFiles.push(mcpPath);
  }
}

function uninstallImpl(opts: AdapterUninstallOptions): AdapterUninstallResult {
  const removed: string[] = [];
  const warnings: string[] = [];
  const hooksPath = resolveProjectHooksPath(opts.cwd);
  if (fs.existsSync(hooksPath)) {
    const file = loadHooksFile(hooksPath);
    for (const event of Object.keys(file.hooks)) {
      const cmds = file.hooks[event];
      const filtered = cmds.filter((c) => !c.command.includes(HOOK_SENTINEL));
      if (filtered.length !== cmds.length) removed.push(event);
      if (filtered.length > 0) file.hooks[event] = filtered;
      else delete file.hooks[event];
    }
    writeJson(hooksPath, file);
  }
  // Remove sentinel block from instructions file (preserve other content).
  const instructionsPath = resolveInstructionsPath(opts.cwd);
  if (fs.existsSync(instructionsPath)) {
    try {
      const raw = fs.readFileSync(instructionsPath, 'utf8');
      const re = new RegExp(`${escapeRegExp(SENTINEL_BEGIN)}[\\s\\S]*?${escapeRegExp(SENTINEL_END)}\\n*`, 'm');
      const next = raw.replace(re, '');
      if (next !== raw) {
        fs.writeFileSync(instructionsPath, next, 'utf8');
      }
    } catch {
      // ignore
    }
  }
  return { configPath: hooksPath, removed, warnings };
}

function detectImpl(home: string, _cwd: string): AdapterDetectResult {
  const installed = fs.existsSync(path.join(home, '.copilot'));
  return { installed, warnings: [] };
}

export const copilotAdapter: Adapter = {
  name: 'copilot',
  // Hooks are observe/policy only; rules file is the dependable injection path
  // and the rules file is regenerated by brain-hook on each sessionStart.
  supportsPreContextInjection: false,
  supportsPromptSubmitInjection: false,
  supportsSessionStartInjection: true,
  install: installImpl,
  uninstall: uninstallImpl,
  detect: detectImpl,
};
