/**
 * Auth routes — invite redemption, login/logout, whoami, rotate.
 *
 * Routes:
 *   POST /api/auth/redeem-invite { invite }        → { pat, tokenId, userId, expiresAt }
 *   POST /api/auth/login         { email, pat }    → { csrfToken, userId, email }   (sets cookie)
 *   POST /api/auth/logout                          → 204                            (cookie-authed)
 *   GET  /api/auth/whoami                          → { userId, email, role, namespace, csrfToken? }
 *   POST /api/auth/rotate        { tokenId? }      → { pat, tokenId, expiresAt }
 *
 * Notes:
 * - `redeem-invite` and `login` are publicly accessible (excluded from
 *   the global auth middleware). `whoami`, `logout`, and `rotate`
 *   require an existing session or PAT.
 * - The session cookie is `Secure; HttpOnly; SameSite=Lax`. CSRF is
 *   enforced for session-authed write requests at the middleware layer.
 */
import { Router, type Response } from 'express';
import { z } from 'zod';
import { verifyInvite } from '../lib/invite.js';
import type { UsersService, Scope } from '../services/users.js';
import { SESSION_COOKIE, type RequestWithUser } from '../middleware/auth.js';

const SESSION_TTL_MS = 7 * 24 * 60 * 60 * 1000; // 7 days
const PAT_TTL_MS = 90 * 24 * 60 * 60 * 1000;    // 90 days

const RedeemInviteSchema = z.object({ invite: z.string().min(8) });
const LoginSchema = z.object({ email: z.email(), pat: z.string().min(1) });
const RotateSchema = z.object({ tokenId: z.string().optional() });

export interface AuthRoutesOptions {
  users: UsersService;
  inviteSigningKey: string | null;
  /** Override clock for tests. */
  now?: () => number;
  /** Whether to set the `Secure` cookie attribute. Default true; tests pass false. */
  secureCookies?: boolean;
}

function setSessionCookie(res: Response, sessionId: string, expiresAt: number, secure: boolean): void {
  const maxAge = Math.max(0, Math.floor((expiresAt - Date.now()) / 1000));
  const parts = [
    `${SESSION_COOKIE}=${encodeURIComponent(sessionId)}`,
    'HttpOnly',
    'Path=/',
    'SameSite=Lax',
    `Max-Age=${maxAge}`,
  ];
  if (secure) parts.push('Secure');
  res.setHeader('Set-Cookie', parts.join('; '));
}

function clearSessionCookie(res: Response): void {
  res.setHeader(
    'Set-Cookie',
    `${SESSION_COOKIE}=; HttpOnly; Path=/; SameSite=Lax; Max-Age=0`,
  );
}

export function authRoutes(options: AuthRoutesOptions): Router {
  const router = Router();
  const { users, inviteSigningKey } = options;
  const now = options.now ?? Date.now;
  const secureCookies = options.secureCookies !== false;

  router.post('/api/auth/redeem-invite', async (req, res, next) => {
    try {
      const body = RedeemInviteSchema.parse(req.body);
      if (!inviteSigningKey) {
        res.status(503).json({ error: 'invites-not-configured' });
        return;
      }

      const verified = verifyInvite(body.invite, inviteSigningKey, { now });
      if (!verified.ok) {
        res.status(400).json({ error: 'invalid-invite', reason: verified.error });
        return;
      }

      // Atomic single-use redemption.
      const consumed = users.consumeInvite(verified.payload.jti);
      if (!consumed) {
        // Either already consumed or not yet inserted. We accept invites
        // generated by the admin path that were registered into invites
        // OR raw HMAC ones (in which case the first redeemer wins).
        const existing = users.getInvite(verified.payload.jti);
        if (!existing) {
          // First-ever redemption for an HMAC-only invite — register and
          // consume in a single step.
          users.insertInvite({
            jti: verified.payload.jti,
            namespace: verified.payload.namespace,
            role: verified.payload.role,
            scopes: verified.payload.scopes.filter((s): s is Scope =>
              s === 'hook:read' || s === 'read' || s === 'write' || s === 'admin',
            ),
            expiresAt: verified.payload.exp,
            consumedAt: now(),
            signature: body.invite,
            createdAt: now(),
          });
        } else {
          res.status(409).json({ error: 'invite-already-consumed' });
          return;
        }
      }

      // Resolve / create the user. Email isn't in the invite payload by
      // design (the invite is per-team-seat, not per-person); we use the
      // jti as the seed so two redeemers get distinct users.
      const placeholderEmail = `${verified.payload.jti}@invite.local`;
      const user = users.upsertUser({ email: placeholderEmail, role: verified.payload.role });
      users.addNamespaceMembership({
        userId: user.id,
        namespace: verified.payload.namespace,
        role: verified.payload.role,
      });

      const scopes = (verified.payload.scopes.length > 0
        ? verified.payload.scopes
        : ['read', 'write']
      ).filter((s): s is Scope =>
        s === 'hook:read' || s === 'read' || s === 'write' || s === 'admin',
      );

      const expiresAt = now() + PAT_TTL_MS;
      const minted = await users.mintPat({
        userId: user.id,
        label: 'invite-redeemed',
        scopes,
        namespace: verified.payload.namespace,
        expiresAt,
      });

      res.status(201).json({
        pat: minted.pat,
        tokenId: minted.tokenId,
        userId: user.id,
        expiresAt: new Date(expiresAt).toISOString(),
      });
    } catch (err) {
      next(err);
    }
  });

  router.post('/api/auth/login', async (req, res, next) => {
    try {
      const body = LoginSchema.parse(req.body);
      const user = users.findUserByEmail(body.email);
      if (!user || user.disabledAt !== null) {
        res.status(401).json({ error: 'invalid-credentials' });
        return;
      }
      const verified = await users.verifyPat(body.pat);
      if (!verified || verified.user.id !== user.id) {
        res.status(401).json({ error: 'invalid-credentials' });
        return;
      }
      const namespace = verified.record.namespace ?? users.listNamespaces(user.id)[0]?.namespace ?? null;
      const expiresAt = now() + SESSION_TTL_MS;
      const session = users.createSession({
        userId: user.id,
        namespace,
        expiresAt,
      });
      setSessionCookie(res, session.id, session.expiresAt, secureCookies);
      res.status(200).json({
        csrfToken: session.csrfToken,
        userId: user.id,
        email: user.email,
      });
    } catch (err) {
      next(err);
    }
  });

  router.post('/api/auth/logout', (req: RequestWithUser, res, next) => {
    try {
      if (req.user?.sessionId) {
        users.deleteSession(req.user.sessionId);
      }
      clearSessionCookie(res);
      res.status(204).end();
    } catch (err) {
      next(err);
    }
  });

  router.get('/api/auth/whoami', (req: RequestWithUser, res) => {
    if (!req.user) {
      res.status(401).json({ error: 'unauthorized' });
      return;
    }
    const csrfToken = req.user.sessionId
      ? users.getSession(req.user.sessionId)?.csrfToken ?? undefined
      : undefined;
    res.json({
      userId: req.user.id,
      email: req.user.email,
      role: req.user.role,
      namespace: req.user.namespace,
      csrfToken,
    });
  });

  router.post('/api/auth/rotate', async (req: RequestWithUser, res, next) => {
    try {
      if (!req.user) {
        res.status(401).json({ error: 'unauthorized' });
        return;
      }
      const body = RotateSchema.parse(req.body ?? {});
      const targetTokenId = body.tokenId ?? req.user.tokenId;
      if (!targetTokenId) {
        res.status(400).json({ error: 'no-token-context' });
        return;
      }
      const found = users.getTokenById(targetTokenId);
      if (!found || found.record.userId !== req.user.id) {
        res.status(404).json({ error: 'token-not-found' });
        return;
      }
      const expiresAt = now() + PAT_TTL_MS;
      const minted = await users.mintPat({
        userId: req.user.id,
        label: found.record.label ?? 'rotated',
        scopes: found.record.scopes,
        namespace: found.record.namespace,
        expiresAt,
      });
      users.revokeToken(targetTokenId);
      res.status(201).json({
        pat: minted.pat,
        tokenId: minted.tokenId,
        expiresAt: new Date(expiresAt).toISOString(),
      });
    } catch (err) {
      next(err);
    }
  });

  return router;
}
